In [7]:
import libpysat as ps
import numpy as np

In [8]:
dir(ps.derived)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

In [123]:
def linear(data, wv_array, axis=0):
    y1 = data[0]
    y2 = data[-1]
    wv1 = wv_array[0]
    wv2 = wv_array[-1]
    m = (y2 - y1) / (wv2 - wv1)    
    b = y1 - (m * wv1)
    wv_array = np.repeat(wv_array, m.size, axis=0).reshape([s for s in data.shape])
    y = (m * wv_array + b)
    return y

In [157]:
arr = np.repeat(np.arange(5), 5).reshape(5,5)
waves = np.asarray([1,2,3,4,5])
arr, waves

(array([[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]]), array([1, 2, 3, 4, 5]))

In [163]:
np.repeat([1,2,3], 1)

array([1, 2, 3])

In [158]:
arr[0]

array([0, 0, 0, 0, 0])

In [162]:
linear(arr[1], [0, 2, 3, 4, 5])

array([ 1.,  1.,  1.,  1.,  1.])

In [122]:
linear(arr, waves)

[[ 13.5 -22.    3.   -7.5  19.5]
 [ 21.   -3.5 -31.5  42.  -23. ]
 [ 14.5  28.    4.   30.5   1. ]
 [  6.5 -20.  -18.   40.5  19.5]
 [  7.5 -17.5 -22.5  18.   35. ]]


array([[[ 58. ,  94. ,   5. ,  26. ,  23. ],
        [ 25. ,  68. ,  92. ,  14. ,  85. ],
        [ 57. ,  12. ,  44. ,  30. ,  64. ],
        [  7. ,  70. ,  88. ,   4. ,   0. ],
        [ 55. ,  62. ,  45. ,   0. ,   5. ]],

       [[ 71.5,  72. ,   8. ,  18.5,  42.5],
        [ 46. ,  64.5,  60.5,  56. ,  62. ],
        [ 71.5,  40. ,  48. ,  60.5,  65. ],
        [ 13.5,  50. ,  70. ,  44.5,  19.5],
        [ 62.5,  44.5,  22.5,  18. ,  40. ]],

       [[ 85. ,  50. ,  11. ,  11. ,  62. ],
        [ 67. ,  61. ,  29. ,  98. ,  39. ],
        [ 86. ,  68. ,  52. ,  91. ,  66. ],
        [ 20. ,  30. ,  52. ,  85. ,  39. ],
        [ 70. ,  27. ,   0. ,  36. ,  75. ]]])

In [3]:
import pandas as pd 

class SubclassedSeries(pd.Series):
    # normal properties
    _metadata = ['tolerance']

    @property
    def _constructor(self):
        return SubclassedSeries

    @property
    def _constructor_expanddim(self):
        return SubclassedDataFrame

class SubclassedDataFrame(pd.DataFrame):
    def __init__(self, *args, **kw):
        super(SubclassedDataFrame, self).__init__(*args, **kw)
        
    @property
    def _constructor(self):
        return SubclassedDataFrame

    @property
    def _constructor_sliced(self):
        return SubclassedSeries

In [4]:
d = pd.DataFrame.from_dict([{'test1': 5.42, 'test2': 22, 'test3' : 33, 45.5:10}]).set_index(['test1', 45.5])
np.is

SyntaxError: invalid syntax (<ipython-input-4-0236aa0288f9>, line 2)

In [ ]:
import numpy as np
x,y = d.index.levels

In [ ]:
def gettype(row):
    return type(row)

def changetype(row):
    row.__class__ = SubclassedSeries
    return type(row)

In [ ]:
# this is a problem
d.apply(gettype, axis=1)