In [84]:
import math
import numpy as np

import libpyhat

from libpyhat.analytics.analytics import band_center, band_area

In [330]:
def band_minima(spectrum, low_endmember=None, high_endmember=None):
    """
    Given two end members, find the minimum observed value inclusively
    between them.

    Parameters
    ==========
    spectrum : nd.Array

    low_endmember : int
                    The low wavelength

    high_endmember : int
                    The high wavelength

    Returns
    =======
    minidx : int
             The wavelength of the minimum value

    minvalue : float
               The observed minimal value
    """
    if not low_endmember:
        low_endmember = 0

    if not high_endmember:
        high_endmember = len(spectrum)
        
    sub_spectrum = spectrum[low_endmember:high_endmember]
    
    minvalue = np.amin(sub_spectrum)
    minidx = np.where(sub_spectrum == minvalue)[0]

    return minidx, minvalue

def band_center(spectrum, low_endmember=None, high_endmember=None, degree=3):

    if not low_endmember:
        low_endmember = 0
        
    if not high_endmember:
        high_endmember = len(spectrum)

    sub_spectrum = spectrum[low_endmember:high_endmember]
    sub_spectrum_indices = list(range(len(sub_spectrum)))
    print(sub_spectrum)

    fit = np.polyfit(sub_spectrum_indices, sub_spectrum, degree)

    center_fit = np.polyval(fit, sub_spectrum_indices)
    center = band_minima(center_fit, low_endmember, high_endmember)

    return center, center_fit

def band_area(spectrum, low_endmember=None, high_endmember=None):
    """
    Compute the area under the curve between two endpoints where the
    y-value <= 1.
    """
    if not low_endmember:
        low_endmember = 0
    if not high_endmember:
        high_endmember = len(spectrum)

    sub_spectrum = spectrum[low_endmember:high_endmember]
    return np.trapz(np.where(sub_spectrum <= 1.0))

def band_asymmetry(spectrum, low_endmember=None, high_endmember=None, degree=3):
    """
    Compute the asymmetry of an absorption feature as
    (left_area - right_area) / total_area

    Parameters
    ----------
    specturm : object

    low_endmember : int
        Bottom end of wavelengths to be obversed

    high_endmember : int
        Top end of wavelengths to be obversed

    Returns
    -------
    asymmetry : ndarray
        Array of percentage values of how asymmetrical the two halves of the spectrum are
        Where 100% is completely asymmetrical and 0 is completely symmetrical
    """

    if not low_endmember:
        low_endmember = 0
        
    if not high_endmember:
        high_endmember = len(spectrum)
    
    sub_spectrum = spectrum[low_endmember:high_endmember]
    
    center, _ = band_center(sub_spectrum, degree=degree)
    print(center)
    center_idx = center[0][math.floor(len(center[0])/2)]

    area_left = band_area(sub_spectrum[:center_idx])

    if len(sub_spectrum) % 2 == 0:
        area_right = band_area(sub_spectrum[center_idx:])
    else:
        area_right = band_area(sub_spectrum[center_idx + 1:])
        
    asymmetry = abs((area_left - area_right) / (area_left + area_right))
    return asymmetry[0]

In [331]:
band_asymmetry(np.array(range(23)), degree=3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
(array([0]), -1.6025121515760643e-15)


/home/acpaquette/anaconda3/envs/libpyhat/lib/python3.6/site-packages/ipykernel_launcher.py:110: RuntimeWarning: invalid value encountered in true_divide


nan

In [325]:
band_asymmetry(np.ones(22), degree=3)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21]), 1.0)


0.0

In [326]:
band_asymmetry(np.ones(21), degree=3)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20]), 1.0)


0.0

In [315]:
band_minima(np.ones(23))

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22]), 1.0)

In [322]:
band_center(np.array(range(23)))

((array([0]), 0),
 array([-1.60251215e-15,  1.00000000e+00,  2.00000000e+00,  3.00000000e+00,
         4.00000000e+00,  5.00000000e+00,  6.00000000e+00,  7.00000000e+00,
         8.00000000e+00,  9.00000000e+00,  1.00000000e+01,  1.10000000e+01,
         1.20000000e+01,  1.30000000e+01,  1.40000000e+01,  1.50000000e+01,
         1.60000000e+01,  1.70000000e+01,  1.80000000e+01,  1.90000000e+01,
         2.00000000e+01,  2.10000000e+01,  2.20000000e+01]))